[versions]
spring-boot = "4.1.0"
spring-doc = "3.1.0"

[libraries]
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
springdoc-openapi-starter-webmvc = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "spring-doc" }
spring-boot-starter-webmvc = { module = "org.springframework.boot:spring-boot-starter-webmvc" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-devtools = { module = "org.springframework.boot:spring-boot-devtools" }
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security" }
spring-boot-starter-security-oauth2-resource-server = { module = "org.springframework.boot:spring-boot-starter-security-oauth2-resource-server" }
postgresql = { module = "org.postgresql:postgresql" }
spring-boot-starter-flyway = { module = "org.springframework.boot:spring-boot-starter-flyway" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

spring-boot-starter-webmvc-test = { module = "org.springframework.boot:spring-boot-starter-webmvc-test" }
spring-boot-starter-data-jpa-test = { module = "org.springframework.boot:spring-boot-starter-data-jpa-test" }
spring-boot-starter-validation-test = { module = "org.springframework.boot:spring-boot-starter-validation-test" }
spring-security-test = { module = "org.springframework.security:spring-security-test" }

[bundles]

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
